version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: anomalias_api
    ports:
      - "8081:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    container_name: anomalias_db
    environment:
      POSTGRES_USER: anomalias_user
      POSTGRES_PASSWORD: anomalias_pass
      POSTGRES_DB: anomalias_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
